--SQLQuery8 - IsWorkingDay.sql
USE PV_521_Import;
SET DATEFIRST 1;
GO

CREATE OR ALTER FUNCTION IsWorkingDay (@date DATE)
RETURNS BIT
AS
BEGIN
	RETURN CASE
		WHEN DATEPART(WEEKDAY, @date) IN (2,4,6,7) THEN 0
		WHEN EXISTS (SELECT 1 FROM DaysOFF WHERE [date] = @date) THEN 0
		ELSE 1
	END
END
